### ISSUE TITLE
 Method Illuminate\Support\Str::replace does not exist.

### ISSUE THREAD

**Issue by Imtiaze** [LarsWiegers/laravel-translations-checker#12]
at D:\wampp\www\paymoney\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:77

    73▕      */
     74▕     public static function __callStatic($method, $parameters)
     75▕     {
     76▕         if (! static::hasMacro($method)) {
    77▕             throw new BadMethodCallException(sprintf(
     78▕                 'Method %s::%s does not exist.', static::class, $method
     79▕             ));
     80▕         }
     81▕

  • Bad Method Call: Did you mean Illuminate\Support\Str::replaceLast() ?

  1   D:\wampp\www\paymoney\vendor\larswiegers\laravel-translations-checker\src\Console\Commands\CheckIfTranslationsAreAllThereCommand.php:78 
      Illuminate\Support\Str::__callStatic("replace")

  2   D:\wampp\www\paymoney\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Larswiegers\LaravelTranslationsChecker\Console\Commands\CheckIfTranslationsAreAllThereCommand::handle()

**Comment by LarsWiegers** [comment]
Hi @Imtiaze, thx for the issue. What php / laravel version are you running?
