### ISSUE TITLE
error: foreach() argument must be of type array|object, int given on line 139

### ISSUE THREAD

**Issue by ordago** [LarsWiegers/laravel-translations-checker#2]
https://github.com/LarsWiegers/laravel-translations-checker/blob/59c0c11000847c86dfafa6daecef13b418aeb77c/src/Console/Commands/CheckIfTranslationsAreAllThereCommand.php#L133-L139

```php
    } catch (\Exception $e) {
        dd([
            '$lines' => $lines,
            '$fileName' => $fileName,
        ]);
    }
```

I checked the values and got this:
```
  array:2 [
    "$lines" => 1
    "$fileName" => "C:\[...]\lang\ca.json"
  ]
```

I didn't pass any argument to the command and it's on a Laravel 9 project with the lang directory in the new place.

**Comment by LarsWiegers** [comment]
Hey! 

Thanks for creating the issue.

Did not know that json files were supported for langs. Thanks for that! 
The package is still mayor WIP. as you can see in the commits haha.

Most likely the include on the json is failing. 

If you want you can create a pr to support json files, or i will take a look at it in the soon future. 

Let me know either way please.

**Comment by ordago** [comment]
Some language string need to be on the json files. e.g. The new password rules:

https://laravel.com/docs/8.x/validation#validating-passwords

I was checking the package but I don't currently have time to dig deeper.

For this purpose use BabelEdit

https://www.codeandweb.com/babeledit

**Comment by LarsWiegers** [comment]
hey thanks, for the fast response.

I will definitly check out BabelEdit

**Comment by LarsWiegers** [comment]
So this actually was fixed. as such closing the issue.
