### ISSUE TITLE
Incorrect missing translation keys

### ISSUE THREAD

**Issue by bgurney** [LarsWiegers/laravel-translations-checker#32]
When I run `translations:check` I get a huge list of incorrect missing translation keys, along the lines of:

```
Missing the translation with key: en-gb.Grenada
Missing the translation with key: .DS_Store.Guadeloupe
Missing the translation with key: en-gb.Guadeloupe
Missing the translation with key: README.md.Guadeloupe
Missing the translation with key: export.Guadeloupe
Missing the translation with key: import.Guadeloupe
Missing the translation with key: en-gb.Guadeloupe
Missing the translation with key: .DS_Store.Guam
Missing the translation with key: en-gb.Guam
```

Our lang directory (in the root of the project) looks like this. There are multiple .php files inside each folder (and yes, we use a non-standard en-gb locale name, but I don't believe this should be an issue)

```
da/
de/
en-gb/
es/
export/
fr/
import/
it/
ni/
no/
pl/
da.ison
de.ison
en-gb.json
es.ison
fr.ison
it.ison
nl.ison
no.json
pl.json
README.md
```

I can confirm that Laravel and it's various starter packs use a combination of PHP and JSON styles in projects as we are doing.

Laravel Breeze, for example:
[PHP style](https://github.com/laravel/breeze/blob/1.x/stubs/default/app/Http/Controllers/Auth/ConfirmablePasswordController.php#:~:text=%27password%27%20%3D%3E-,__(%27auth.password%27),-%2C)
[JSON style](https://github.com/laravel/breeze/blob/1.x/stubs/default/resources/views/profile/edit.blade.php#:~:text=%7B%7B-,__(%27Profile%27),-%7D%7D)

I've never seen JSON files being used in the sub-folders though and can't see any mention of this in the [docs](https://laravel.com/docs/10.x/localization#defining-translation-strings).

We also use the [Laravel-Lang](https://laravel-lang.com/) project, which provides boilerplate translations for a whole load of these things in both styles. So useful!

**Comment by LarsWiegers** [comment]
Closing as I have not heard back by @bgurney
