### ISSUE TITLE
Fails to find all translation keys

### ISSUE THREAD

**Issue by T5000** [LarsWiegers/laravel-translations-checker#35]
Some translation keys seem to be ignored;
There are some translation keys in my project that get overlooked when I run `php artisan translations:check` - the command returns
`✔ All translations are okay!`, but it is clear there are keys that do not have any translations defined.
All the keys that are missing translations, and get missed by `translations:check` command seem to appear multiple times in same blade files.
Could this be the cause of the issue?

Very cool project though, saved me a lot of time. You have my thanks!

**Comment by LarsWiegers** [comment]
HI @T5000 thanks for the issue.

So If I understand correctly you have translations in blade that are not defined in translations files?
And you expect the translation:check to make sure that you defined them in translation files?

That is not what the command is currently designed for.
For now, it only checks if the translation you have defined in one language also exists in the other languages. 

Could you explain some more about your situation, what is your lang folder structure like / the blade file you mention? Thanks in advance!

**Comment by T5000** [comment]
Hello @LarsWiegers, thank you for the reply!

Yes, that is correct, I have many translations in blade files, some even live in controllers for various ajax requests.

I must have misunderstood the [laravel-translations-checker](https://github.com/LarsWiegers/laravel-translations-checker) description when I skimmed it, I was under the impression this finds all translation keys in a Laravel project and makes sure they are defined in all languages! My bad :(

The package works just fine for finding all translations that are defined in some but not other languages.



My reasons for this request:
1. While I do my best to always define translations immediately when making new pages/content, it does sometimes slip my mind, and I'd like to have an automated tool that tells me what I missed.
2. When writing code and defining new translation keys, I'd prefer to keep my focus on the code instead of switching to translation file(s) to copy/paste each new key. 

My lang folder structure is the default one - everything is in the resources/lang folder, where 2 letter locale folders (en, de, ...) contain .php files with translations, and also there are en.json, de.json, etc. files that have many phrases and texts that appear on our website.
