### ISSUE TITLE
ignore files in /lang with a specific extension

### ISSUE THREAD

**Issue by valh1996** [LarsWiegers/laravel-translations-checker#47]
Hi,

I'm using `laravel-vue-i18n` package: https://github.com/xiCO2k/laravel-vue-i18n

And as the doc says:
>During the npm run dev execution time, the plugin will create some files like this php_{lang}.json on your lang folder.

Given that `laravel-translations-checker` will already be checking .php lang files, is it possible to ignore this `php_{lang}.json` files please?

**Comment by LarsWiegers** [comment]
Hi @valh1996 so this is currently not supported, let me see if I can hack this up for you.

**Comment by LarsWiegers** [comment]
Just merged the pr and will create a new version for you, should be available in the next hour or so.

**Comment by LarsWiegers** [comment]
Closing for now, but if it does not work feel free to re open.
